title: "Plawan - Your Personal Finance Everything"
email: admin@plawan.com.np
timezone: UTC
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Plawan
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  Plawan:
    name: Plawan Ghimire
    display_name: Plawan
    avatar: 'assets/images/sal.png'
    email: plawan@plawan.com.np
    web: https://plawan.com.np/
    description: "Author of plawan.com.np, a blog with everything a college student would need for their personal finance and financial freedom."

# Social
social:
  instagram: https://instagram.com/itsplawan_
  

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives